name: logistics-platform

services:

  # Postgres
  postgres:
    image: postgres:16-alpine
    container_name: logistics-postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Так контейнер НЕ использует анонимный volume, который удаляется при docker-compose down -v
      - ./postgres:/docker-entrypoint-initdb.d
    healthcheck: # Проверка готовности PostgreSQL принимать запросы
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # MongoDB
  mongodb:
    image: mongo:7
    container_name: logistics-mongodb
    environment:
#      MONGO_INITDB_ROOT_USERNAME: root  # 👈 ЗАКОММЕНТИРОВАЛ для разработки, потом включу (без аутентификации для разработки)
#      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: logistics_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db   # 👈именую volume
    healthcheck: # Проверка готовности MongoDB
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 🟢 ВЕБ-АДМИНКА ДЛЯ ПРОСМОТРА MONGO ЧЕРЕЗ БРАУЗЕР (ДОБАВЛЕНО СЮДА)
  mongo-express:
    image: mongo-express:latest
    container_name: logistics-mongo-express
    restart: always
    depends_on:
      mongodb:
        condition: service_healthy # Ждем, пока Mongo успешно пройдет свой пинг-тест
    ports:
      - "8081:8081" # Порт, который будем открывать в браузере
    environment:
      ME_CONFIG_MONGODB_SERVER: logistics-mongodb # Имя контейнера Mongo, к которому подключаемся
      ME_CONFIG_MONGODB_PORT: 27017

      # 🟢 ОТКЛЮЧАЕМ ТРЕБОВАНИЕ ПАРОЛЯ ПРИ ВХОДЕ В БРАУЗЕР (для разработки) // по умолчанию: Username:admin Password:pass
      ME_CONFIG_BASICAUTH: "false"


# Добавляю теперь   keycloak:
  postgres-keycloak:
    image: postgres:16-alpine
    container_name: logistics-postgres-keycloak
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=keycloak
    ports:
      - "5433:5432"
    volumes:
      - postgres_keycloak_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: logistics-keycloak
    depends_on:
      - postgres-keycloak
    command: [ "start-dev", "--import-realm" ]
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres-keycloak
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import
      - ./keycloak/exports:/tmp/keycloak-export

volumes:
  postgres_data:
  mongo_data:
  postgres_keycloak_data:
