name: logistics-platform-dev

services:
  # PostgreSQL для user-service
  postgres:
    image: postgres:16-alpine
    container_name: logistics-postgres
    environment:
      POSTGRES_DB: logistics_user_db
      POSTGRES_USER: logistics_user
      POSTGRES_PASSWORD: logistics_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./local/postgres:/docker-entrypoint-initdb.d   # ✅ для контроля
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U logistics_user -d logistics_user_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # MongoDB
  mongodb:
    image: mongo:7
    container_name: logistics-mongodb
#    environment:         # 👈 ЗАКОММЕНТИРОВАЛ для разработки, потом включу (без аутентификации для разработки)
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: root
#      MONGO_INITDB_DATABASE: logistics_logs
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  mongo_data: